### PR TITLE
Update section 5.1.2 of the spec - explicit mention that CNI Plugin can update CNIDeviceInfoFile

### PR DESCRIPTION
**Pull request by ykulazhenkov**
Add explicit mention that CNI Plugin can also update content of the file in CNIDeviceInfoFile path.

The current spec version defines that CNI Plugin can read and write DeviceInfoFile, but update operation is not defined explicitly.
Add mention of update operation explicitly for clarity.

### CODE REVIEW

**Comment by ykulazhenkov** [comment]
cc @adrianchiris

**Review by adrianchiris — APPROVED** [review]
LGTM,

The context is the recently added `representor-device` field added to the spec.

accelerated-bridge-cni will update the pci device entry with the representor device.

https://github.com/k8snetworkplumbingwg/accelerated-bridge-cni/pull/53

**Review by SchSeba — APPROVED** [review]

**Comment by ykulazhenkov** [comment]
@amorenoz  @dougbtv 
Please take a look at this PR.
Can we merge it?

**Comment by amorenoz** [comment]
Thanks for the context @adrianchiris.
Do we need to specify which fields can the updated by the CNI in order to avoid conflicts?

**Comment by adrianchiris** [comment]
> Do we need to specify which fields can the updated by the CNI in order to avoid conflicts?

we can either be loose and not specify OR say that updating is allowed for fields which were not previously set.
thoughts ?

i dont think we need to start listing fields that are "allowed to be updated"

for our use-case, cni adds information to a field which was empty before

**Review by amorenoz — APPROVED** [review]
I don't see any reason why we cannot be loose here and adding rw information to each field seems an overkill.
LGTM. Thanks @ykulazhenkov and @adrianchiris

**Pull request merged**
